//Write your function calls below this line
setColor(6, 2, "red")
setColor(6, 3, "red")
setColor(6, 4, "red")
setColor(6, 5, "red")
setColor(6, 6, "red")
setColor(6, 7, "red")
setColor(6, 8, "red")
setColor(6, 1, "red")
setColor(2, 2, "red")
setColor(3, 2, "red")
setColor(4, 2, "red")
setColor(4, 3, "red")
setColor(3, 3, "red")
setColor(2, 3, "red")
setColor(2, 6, "red")
setColor(2, )
setColor(2)
setColor()
